### PR TITLE
⚠️ Moving Control Plane Provider and Infra Provider

### LINKED ISSUE #45: ⚠️ Move controlplane.cluster.x-k8s.io components to controlplane/
When we look at other CAPI implementations instead of using `multi-group` controllers they typically are deployed as independent controllers, they're even built this way, for example see kcp in `controlplane/kubeadm/` in https://github.com/kubernetes-sigs/cluster-ap while the main types `NestedCluster` in our world live usually at the top level, eg https://github.com/kubernetes-sigs/cluster-api-provider-aws you can even see the `eks` controlplane is built in `controlplane/eks/` https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/main/controlplane/eks.

We should adjust to having the 4 `controlplane` group's resources in `controlplane/nested/` and have only the top level `NestedCluster` at `/` this will also make it easier to co-operate if we eventually transition to kcp (eg #44)

### PR DESCRIPTION
**Pull request by christopherhein**
This PR separates the Control Plane Provider from the Infrastructure provider allowing them to be deployed separately which will help us down the line if we end up wanting to support #44 but also helps us to better the experience for `clusterctl` once we get our first release out to help fulfill #54.

### Create `kind` cluster

```bash
kind create cluster
```

### Install `cert-manager`

```bash
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.yaml
```

### Clone CAPI and Deploy Dev release

We need to deploy the unreleased version of CAPI for `v1alpha4` API support.

```bash
git clone git@github.com:kubernetes-sigs/cluster-api.git
cd cluster-api
make release-manifests
# change feature flags on core
sed -i'' -e 's@- --feature-gates=.*@- --feature-gates=MachinePool=false,ClusterResourceSet=true@' out/core-components.yaml
kubectl apply -f out/core-components.yaml
```

### Create Docker Images, Manifests and Load Images

```bash
export PULL_POLICY=Never
export TAG=dev
make docker-build release-manifests
kind load docker-image gcr.io/cluster-api-nested-controller-amd64:dev
kind load docker-image gcr.io/nested-controlplane-controller-amd64:dev
```

### Deploy CAPN

```bash
kubectl apply -f out/cluster-api-provider-nested-components.yaml
```

### Apply Sample Cluster

```bash
kubectl apply -f config/samples/
```

### Get `KUBECONFIG`

```bash
clusterctl get kubeconfig cluster-sample > kubeconfig
```

### Port Forward

In a separate shell, you will need to `port-forward` the apiserver service.

```bash
kubectl port-forward svc/cluster-sample-apiserver 6443:6443
```

### Connect to Cluster

To use the `KUBECONFIG` without modification we first need to setup a host record for the 
apiserver service name, to do this we can append that to `/etc/hosts`

```bash
cat /etc/hosts
# Normal hosts file
127.0.0.1 cluster-sample-apiserver
```

### Connect to the Cluster! 🎉 

```bash
kubectl --kubeconfig kubeconfig get all -A
```

## Related
Closes #45 

Signed-off-by: Chris Hein <me@chrishein.com>

### CODE REVIEW

**Comment by christopherhein** [comment]
@charleszheng44 the description of this PR has most of the steps laid out for the initial tutorial, I didn't write these up in docs yet if you'd still like to do that for #52

**Comment by Fei-Guo** [comment]
LGTM

**Comment by charleszheng44** [comment]
> @charleszheng44 the description of this PR has most of the steps laid out for the initial tutorial, I didn't write these up in docs yet if you'd still like to do that for #52

Yes. I will try this out and write up the tutorial for the first release.

**Pull request merged**
