### PR TITLE
🌱 Update for picking up cluster-api v0.4.0

### PR DESCRIPTION
**Pull request by wangjsty**
**What this PR does / why we need it**:

Update cluster-api to v0.4.0

util.ManagerDelegatingClientFunc has been removed
This function was originally used to generate a delegating client when creating a new manager.
Controller Runtime v0.9.x now uses a ClientBuilder in its Options struct and it uses the delegating client by default under the hood, so this can be now removed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/189

### CODE REVIEW

**Comment by wangjsty** [comment]
@christopherhein @Fei-Guo

**Comment by christopherhein** [comment]
/ok-to-test

@wangjsty you've been doing a decent amount of work in this project, to help make feedback a little faster have you started the process to join the Kubernetes org? - https://git.k8s.io/community/community-membership.md#member

I'm sure some of us can help support/lgtm your application.

**Comment by wangjsty** [comment]
@christopherhein @Fei-Guo How can I run all tests in my local environment?

**Comment by christopherhein** [comment]
> @christopherhein @Fei-Guo How can I run all tests in my local environment?

You can run `make test` in both the root `/` of the repo and the `/virtualcluster` dir

**Comment by christopherhein** [comment]
/lgtm
/approved

thank you for doing this!

**Comment by christopherhein** [comment]
/lgtm
/approve

thank you for doing this!

**Pull request merged**
