### PR TITLE
✨ Add golangci-lint for virtual cluster project

### PR DESCRIPTION
**Pull request by m-messiah**
**What this PR does / why we need it**:
Previously virtualcluster object has no linting and had some static golang problems or readability issues.
The PR is intended to enable linting for the directory.
As the initial run showed more than 2500 issues the PR consists of many commits for enabling golangci-lint checkers one by one.

### CODE REVIEW

**Comment by Fei-Guo** [comment]
Again, thanks for the awesome improvement. Please fix the conflicts.

**Comment by m-messiah** [comment]
rebased

**Review by christopherhein — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
