### PR TITLE
Correct manifest path since the file name has been changed in previously ccommit

### PR DESCRIPTION
**Pull request by vincent-pli**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by christopherhein** [comment]
Whoops, this is probably going to need more updates to work correctly, because the images aren't published anywhere this manifest will fail to be used for any cluster that you don't run `make build-images` and thus don't push those images into the kind or minikube cluster, it also requires CAPN which will require the user to do and follow the `docs/README.md`.

Given this isn't ready how should we handle the updates to this? Should we revert since you should be able to use VC w/o CAPN right now via the old readme, and then once we get #129 and #130 ?

**Comment by christopherhein** [comment]
@Fei-Guo @vincent-pli ^^^^

**Comment by Fei-Guo** [comment]
@christopherhein Yes. I think you overwrote the old all_in_one with all_in_one_capi?  can you add the old all_in_one back and revert the README to the old all_in_one?

**Comment by christopherhein** [comment]
Oh shoot, wow. sorry I missed that, yea we can add that manifest back.

**Pull request merged**
