### PR TITLE
🐛Fix VirtualCluster CRD and reconciler for work in 1.19+1.20 environment

### PR DESCRIPTION
**Pull request by m-messiah**
**What this PR does / why we need it**:
When the super cluster has two different versions of API Server (specifically 1.19 and 1.20) it results in errors of vc-manager, as 1.20 added non-nullable nulls https://github.com/kubernetes/kubernetes/pull/95423, while 1.19 can't work with them.

```
{"level":"error","ts":1664969234.2211943,"logger":"controller-runtime.manager.controller.virtualcluster","msg":"Reconciler error","reconciler group":"tenancy.x-k8s.io","reconciler kind":"VirtualCluster","name":"test","namespace":"default","error":"VirtualCluster.tenancy.x-k8s.io \"test\" is invalid: [status.reason: Invalid value: \"null\": status.reason in body must be of type string: \"null\", status.message: Invalid value: \"null\": status.message in body must be of type string: \"null\", status.phase: Invalid value: \"null\": status.phase in body must be of type string: \"null\"]"}

{"level":"error","ts":1664975149.3489153,"logger":"controller-runtime.manager.controller.virtualcluster","msg":"Reconciler error","reconciler group":"tenancy.x-k8s.io","reconciler kind":"VirtualCluster","name":"test","namespace":"default","error":"VirtualCluster.tenancy.x-k8s.io \"test\" is invalid: status.conditions.status: Invalid value: \"null\": status.conditions.status in body must be of type string: \"null\""}
```

So the first solution is to set LastTransitionTime to be a pointer (as metav1.Time is not nullable https://github.com/kubernetes/kubernetes/issues/86811
And the second solution is to set status.condition.Status to non-empty string (as it expected initially). I set it always True, as we don't have false conditions, but we could improve it later.

With these two changes vc-manager became working again.

**Which issue(s) this PR fixes**:
The PR is related to https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/63, but I am not sure it could fix all the things there

### CODE REVIEW

**Comment by Fei-Guo** [comment]
I am a little confused about the problematic version combination of vc, vc-manager, super. Can you provide the details of the following?

vc apiserver version: ?
vc-manager client-go version: ?
super apiserver version: ?

**Comment by m-messiah** [comment]
vc apiserver version: does not matter. Happens with 1.19 and 1.20 as well
vc-manager client-go version: latest commit https://github.com/kubernetes-sigs/cluster-api-provider-nested/commit/e55cc6f87f61edc1fa028c4ba11a69c5e5b4330a ,  v0.21.9 as I see in go.mod
super apiserver version: v1.19.13 + v1.20.15 on several nodes


So the main problem here is we have two apiserver versions in the super cluster during migration upgrade, that leads to incorrectly set CRs (by api 1.20), that are needed to be handled by 1.19.13 apiserver.

**Comment by Fei-Guo** [comment]
@christopherhein Yes, this is crd field type change without bumping the version. I am not sure if existing CRs need to be converted to make controller or cr list/get work.

**Comment by m-messiah** [comment]
We found that the problem was deeper than it looked, especially after additional checks that this PR changes did not help. 
The root cause of the issue is described here https://github.com/kubernetes/kubernetes/issues/99804 and fixed there https://github.com/kubernetes/kube-openapi/pull/230 and it happened for our cluster where we had couple Kubernetes API Servers built with Golang 1.16, that failed the validation. 

The fast and only solution is to rebuilt the server with Go 1.15, as only Kube APIServer 1.21.0+ has the bugfix for 1.16 compatibility included

**Pull request closed without merging**
